#!/usr/bin/env bash
# ==============================================================================
# 03-docker-deploy.sh —— 单机版 Docker 一键部署 / 健康检查 / 回滚
#
# 设计：
#   - 既可在本机通过 SSH 远程驱动远端执行（自动识别），也可直接在远端
#     /usr/local/services/mawuya/current 目录下运行。
#   - 自动生成 Dockerfile（AMS / BMS）与 docker-compose.yml
#   - docker compose up -d 启动 mysql / mawuya-ams / mawuya-bms 三个服务
#   - 内置 healthcheck 等待 AMS:8080 / BMS:8081 就绪
#   - 失败自动回滚到上一个 release 软链接（releases/<上一次时间戳>）
#
# 子命令：
#   up         构建并启动（默认）
#   down       停止并清理容器（保留数据卷）
#   logs       跟踪日志
#   status     查看容器与端口状态
#   rollback   切换到上一次 release 并重启
# ==============================================================================

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/common.sh" 2>/dev/null || {
    # 当此脚本被发到远端独立执行时，lib 在同级目录
    source "${SCRIPT_DIR}/lib/common.sh"
}

ACTION="${1:-up}"

# 远程驱动模式：若在编译机执行且尚未在远端，则改为通过 SSH 调用远端版本
if [[ ! -d "${SCRIPT_DIR}/../jars" ]] && [[ -n "${SSH_HOST:-}" ]] && [[ "${MAWUYA_REMOTE_RUN:-0}" != "1" ]]; then
    log_step "通过 SSH 在远端执行 03-docker-deploy.sh ${ACTION}"
    test_ssh || die "无法连接远端"
    remote_exec "cd ${REMOTE_DEPLOY_DIR}/current && \
        export MAWUYA_REMOTE_RUN=1 AMS_PORT=${AMS_PORT} BMS_PORT=${BMS_PORT} MYSQL_PORT=${MYSQL_PORT} \
               MYSQL_ROOT_PASSWORD='${MYSQL_ROOT_PASSWORD:-ChangeMe_Root_2026}' \
               MYSQL_DATABASE='${MYSQL_DATABASE:-blog}' \
               MYSQL_USER='${MYSQL_USER:-mawuya}' \
               MYSQL_PASSWORD='${MYSQL_PASSWORD:-ChangeMe_App_2026}' && \
        bash scripts/03-docker-deploy.sh ${ACTION}"
    exit $?
fi

# ============== 远端本地执行段 ==============
# 此分支假设我们已经在远端 ${REMOTE_DEPLOY_DIR}/current 目录里
RELEASE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"  # current 实际目录
DEPLOY_PARENT_DIR="$(cd "${RELEASE_DIR}/.." && pwd)"  # releases/
MAWUYA_HOME="$(cd "${DEPLOY_PARENT_DIR}/.." && pwd)"  # /usr/local/services/mawuya
JARS_DIR="${RELEASE_DIR}/jars"
SQL_DIR="${RELEASE_DIR}/sql"
DOCKER_DIR="${RELEASE_DIR}/docker"
COMPOSE_FILE="${MAWUYA_HOME}/docker-compose.yml"

require_compose() {
    if docker compose version >/dev/null 2>&1; then
        DC="docker compose"
    elif have_cmd docker-compose; then
        DC="docker-compose"
    else
        die "未安装 docker compose，请先运行 01-precheck.sh"
    fi
    export DC
}

# 生成 Dockerfile 与 compose 文件（若不存在）
gen_docker_files() {
    log_step "生成 Dockerfile 与 docker-compose.yml"
    mkdir -p "${MAWUYA_HOME}/docker"

    # 基础镜像：可通过环境变量覆盖（如改用 alibaba dragonwell、国内 mirror tag 等）
    : "${BASE_IMAGE:=eclipse-temurin:8-jre-jammy}"
    : "${MYSQL_IMAGE:=mysql:5.7}"

    # 公共 base：抽出 FROM 层，避免 AMS / BMS 重复拉
    cat > "${MAWUYA_HOME}/docker/Dockerfile.base" <<EOF
# Auto-generated common base
FROM ${BASE_IMAGE}
WORKDIR /app
ENV JAVA_OPTS="-Xms256m -Xmx512m -Djava.security.egd=file:/dev/./urandom"
EOF

    # AMS Dockerfile —— FROM 本地 base，jar 改动只重建最后一层
    cat > "${MAWUYA_HOME}/docker/Dockerfile.ams" <<EOF
FROM mawuya/base:jre8
LABEL app="mawuya-ams"
COPY ${AMS_JAR_NAME} /app/app.jar
EXPOSE ${AMS_PORT}
HEALTHCHECK --interval=15s --timeout=5s --start-period=40s --retries=5 \\
    CMD curl -fsS http://127.0.0.1:${AMS_PORT}/ >/dev/null || exit 1
ENTRYPOINT ["sh","-c","exec java \$JAVA_OPTS -jar /app/app.jar"]
EOF

    cat > "${MAWUYA_HOME}/docker/Dockerfile.bms" <<EOF
FROM mawuya/base:jre8
LABEL app="mawuya-bms"
COPY ${BMS_JAR_NAME} /app/app.jar
EXPOSE ${BMS_PORT}
HEALTHCHECK --interval=15s --timeout=5s --start-period=40s --retries=5 \\
    CMD curl -fsS http://127.0.0.1:${BMS_PORT}/bms/login.do >/dev/null || exit 1
ENTRYPOINT ["sh","-c","exec java \$JAVA_OPTS -jar /app/app.jar"]
EOF

    # 把当前 release 的 jar 拷贝到 docker 目录（构建上下文）
    cp -f "${JARS_DIR}/${AMS_JAR_NAME}" "${MAWUYA_HOME}/docker/"
    cp -f "${JARS_DIR}/${BMS_JAR_NAME}" "${MAWUYA_HOME}/docker/"

    # 准备 SQL 初始化脚本（首次启动 mysql 容器时自动执行）
    mkdir -p "${MAWUYA_HOME}/initdb"
    if [[ -f "${SQL_DIR}/schema.sql" ]]; then
        cp -f "${SQL_DIR}/schema.sql" "${MAWUYA_HOME}/initdb/01-schema.sql"
    fi
    if [[ -f "${SQL_DIR}/data.sql" ]]; then
        cp -f "${SQL_DIR}/data.sql" "${MAWUYA_HOME}/initdb/02-data.sql"
    fi

    # docker-compose.yml
    cat > "${COMPOSE_FILE}" <<EOF
# Auto-generated by 03-docker-deploy.sh on $(date '+%F %T')
version: "3.8"

networks:
  mawuya-net:
    driver: bridge

volumes:
  mawuya-mysql-data:

services:
  mysql:
    image: ${MYSQL_IMAGE}
    container_name: mawuya-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-ChangeMe_Root_2026}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-blog}"
      MYSQL_USER: "${MYSQL_USER:-mawuya}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-ChangeMe_App_2026}"
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mawuya-mysql-data:/var/lib/mysql
      - ${MAWUYA_HOME}/initdb:/docker-entrypoint-initdb.d:ro
    networks: [mawuya-net]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p\$\$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  mawuya-ams:
    build:
      context: ${MAWUYA_HOME}/docker
      dockerfile: Dockerfile.ams
    image: mawuya/ams:latest
    container_name: mawuya-ams
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-blog}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER:-mawuya}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD:-ChangeMe_App_2026}"
      SERVER_PORT: "${AMS_PORT}"
    ports:
      - "${AMS_PORT}:${AMS_PORT}"
    networks: [mawuya-net]

  mawuya-bms:
    build:
      context: ${MAWUYA_HOME}/docker
      dockerfile: Dockerfile.bms
    image: mawuya/bms:latest
    container_name: mawuya-bms
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-blog}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER:-mawuya}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD:-ChangeMe_App_2026}"
      SERVER_PORT: "${BMS_PORT}"
    ports:
      - "${BMS_PORT}:${BMS_PORT}"
    networks: [mawuya-net]
EOF
    log_ok "Dockerfile / docker-compose.yml 已生成在 ${MAWUYA_HOME}"
}

wait_health() {
    local name="$1" url="$2" max_wait="${3:-120}"
    log_info "等待 ${name} 健康（最多 ${max_wait}s）：${url}"
    local elapsed=0
    while (( elapsed < max_wait )); do
        if curl -fsS --max-time 3 "${url}" >/dev/null 2>&1; then
            log_ok "${name} 已就绪"
            return 0
        fi
        sleep 3
        elapsed=$((elapsed+3))
        printf '.'
    done
    echo
    log_error "${name} 健康检查超时"
    return 1
}

# 记录上一个成功 release，便于回滚
mark_last_good() {
    local cur
    cur="$(readlink -f "${MAWUYA_HOME}/current")"
    echo "${cur}" > "${MAWUYA_HOME}/.last_good_release"
}

rollback_to_last_good() {
    log_step "失败回滚"
    if [[ ! -f "${MAWUYA_HOME}/.last_good_release" ]]; then
        log_warn "未找到上一次成功记录，仅停止当前容器"
        ${DC} -f "${COMPOSE_FILE}" down || true
        return 1
    fi
    local prev
    prev="$(cat "${MAWUYA_HOME}/.last_good_release")"
    if [[ -d "${prev}" ]]; then
        log_warn "回滚 current 软链接 -> ${prev}"
        ln -sfn "${prev}" "${MAWUYA_HOME}/current"
        # 用上一次的 jar 重建并启动
        cp -f "${prev}/jars/${AMS_JAR_NAME}" "${MAWUYA_HOME}/docker/"
        cp -f "${prev}/jars/${BMS_JAR_NAME}" "${MAWUYA_HOME}/docker/"
        ${DC} -f "${COMPOSE_FILE}" up -d --build mawuya-ams mawuya-bms
        log_warn "已回滚到上一次成功版本，请检查应用状态"
    else
        log_error "上一次目录不存在：${prev}"
        return 1
    fi
}

# 预拉所需镜像（带重试 + 容错；如果远端已 docker load 了 tar 则会自动跳过）
# 单独 pull 比 compose build 时再 pull 更可控，便于失败时排查
prepull_images() {
    : "${BASE_IMAGE:=eclipse-temurin:8-jre-jammy}"
    : "${MYSQL_IMAGE:=mysql:5.7}"

    log_step "预拉基础镜像（已存在则秒过）"
    for img in "${BASE_IMAGE}" "${MYSQL_IMAGE}"; do
        if docker image inspect "${img}" >/dev/null 2>&1; then
            log_ok "已存在：${img}"
            continue
        fi
        log_info "拉取：${img}"
        local n=1
        until docker pull "${img}"; do
            if (( n >= 3 )); then
                log_error "拉取 ${img} 失败，请检查 /etc/docker/daemon.json 镜像加速或网络"
                log_error "建议在本机预先 docker save 该镜像并 scp 上来 docker load"
                return 1
            fi
            log_warn "第 ${n} 次拉取失败，5s 后重试..."
            sleep 5; n=$((n+1))
        done
    done

    # 构建公共 base 镜像（只构建一次，无网络下载）
    if ! docker image inspect mawuya/base:jre8 >/dev/null 2>&1; then
        log_info "构建公共 base 镜像 mawuya/base:jre8"
        docker build -t mawuya/base:jre8 -f "${MAWUYA_HOME}/docker/Dockerfile.base" "${MAWUYA_HOME}/docker"
    else
        log_ok "已存在：mawuya/base:jre8"
    fi
}

cmd_up() {
    require_compose
    require_cmd docker curl
    gen_docker_files
    prepull_images || die "镜像准备失败，部署中止"

    log_step "docker compose up -d --build"
    # pull_policy: missing 让 compose 不再去重复 pull 已有镜像
    ${DC} -f "${COMPOSE_FILE}" up -d --build --pull missing

    log_step "容器状态"
    ${DC} -f "${COMPOSE_FILE}" ps

    # 健康检查（使用宿主端口，绕过容器内部 curl 依赖）
    local ok=1
    wait_health "AMS" "http://127.0.0.1:${AMS_PORT}/"             180 || ok=0
    wait_health "BMS" "http://127.0.0.1:${BMS_PORT}/bms/login.do" 180 || ok=0

    if [[ "${ok}" -eq 1 ]]; then
        mark_last_good
        log_step "部署成功"
        echo "  AMS  访客前台 : http://<host>:${AMS_PORT}/"
        echo "  BMS  后台管理 : http://<host>:${BMS_PORT}/bms/login.do  (默认 admin/123456，请尽快修改)"
        echo "  日志：${DC} -f ${COMPOSE_FILE} logs -f mawuya-ams mawuya-bms"
    else
        log_error "服务未通过健康检查，开始回滚"
        ${DC} -f "${COMPOSE_FILE}" logs --tail=200 mawuya-ams mawuya-bms || true
        rollback_to_last_good || true
        exit 1
    fi
}

cmd_down() {
    require_compose
    log_step "停止并移除容器（保留数据卷）"
    ${DC} -f "${COMPOSE_FILE}" down
    log_ok "已停止"
}

cmd_logs() {
    require_compose
    ${DC} -f "${COMPOSE_FILE}" logs -f --tail=200 mawuya-ams mawuya-bms
}

cmd_status() {
    require_compose
    ${DC} -f "${COMPOSE_FILE}" ps
    echo
    log_info "端口监听："
    ss -ltnp 2>/dev/null | awk -v a=":${AMS_PORT}" -v b=":${BMS_PORT}" -v c=":${MYSQL_PORT}" \
        '$4 ~ a || $4 ~ b || $4 ~ c {print}' || true
}

cmd_rollback() {
    require_compose
    rollback_to_last_good
}

# 快速更新：只重建并重启 AMS / BMS（不动 MySQL，不重拉基础镜像）
# 适合：仅 jar 改动的常规迭代发布，比 cmd_up 节省 80% 以上时间
cmd_update() {
    require_compose
    require_cmd docker curl
    gen_docker_files

    # base 镜像若不存在仍需构建，但已存在则秒过
    if ! docker image inspect mawuya/base:jre8 >/dev/null 2>&1; then
        log_warn "未发现 base 镜像，先执行一次全量预拉"
        prepull_images || die "镜像准备失败"
    fi

    log_step "重建 AMS / BMS 镜像并替换容器（MySQL 保持运行）"
    ${DC} -f "${COMPOSE_FILE}" build mawuya-ams mawuya-bms
    # --no-deps 不会触动 mysql；--force-recreate 确保新镜像生效
    ${DC} -f "${COMPOSE_FILE}" up -d --no-deps --force-recreate mawuya-ams mawuya-bms

    log_step "容器状态"
    ${DC} -f "${COMPOSE_FILE}" ps

    local ok=1
    wait_health "AMS" "http://127.0.0.1:${AMS_PORT}/"             180 || ok=0
    wait_health "BMS" "http://127.0.0.1:${BMS_PORT}/bms/login.do" 180 || ok=0

    if [[ "${ok}" -eq 1 ]]; then
        mark_last_good
        log_ok "快速更新完成 ✅"
    else
        log_error "健康检查失败，开始回滚"
        ${DC} -f "${COMPOSE_FILE}" logs --tail=200 mawuya-ams mawuya-bms || true
        rollback_to_last_good || true
        exit 1
    fi
}

case "${ACTION}" in
    up)       cmd_up ;;
    update)   cmd_update ;;
    down)     cmd_down ;;
    logs)     cmd_logs ;;
    status)   cmd_status ;;
    rollback) cmd_rollback ;;
    *) die "未知子命令：${ACTION}（up|update|down|logs|status|rollback）" ;;
esac
